global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask'
    static_configs:
      - targets: ['web:8000']  # Prometheus metrics endpoint
  - job_name: 'celery'
    static_configs:
      - targets: ['flower:5555']  # Flower's Prometheus exporter
